"""Add number column to test table

Revision ID: 176e6a96abe1
Revises: 088e516dfb8a
Create Date: 2022-10-15 21:10:37.644752

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "176e6a96abe1"
down_revision = "088e516dfb8a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("test_table", sa.Column("number", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_table", "number")
    # ### end Alembic commands ###
